/**
 * Copyright 2008 Pavel Syrtsov
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations
 * under the License.
 */

package net.sf.fisolator;

import java.util.concurrent.*;
import java.util.List;
import java.util.ArrayList;

/**
 * This is the main class for fault isolation framework, it allows differnet types of calls to callable that to be isolated: <br/>
 * <li> enqueue methods - async execution of callable 
 * <li> invoke methods - sync execution with timeout
 * Created by: Pavel Syrtsov
 * Date: Aug 24, 2008
 * Time: 10:37:56 AM
 */
public class FaultIsolator {
    private long startTime = System.currentTimeMillis();
    private List<TaskData> taskDataList = new ArrayList<TaskData>();
    private ExecutorService executor;

    public FaultIsolator(ExecutorService executor) {
        this.executor = executor;
    }

    public long getStartTime() {
        return startTime;
    }

    public List<TaskData> getTaskDataList() {
        return taskDataList;
    }

    public ExecutorService getExecutor() {
        return executor;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public void setExecutor(ExecutorService executor) {
        this.executor = executor;
    }

    public<T> Future enqueue(final Callable<T> callable, final FeatureFaultIsolator feature) {
        if(!feature.isAvailable()) {
            return null;
        }
        feature.taskAccepted(callable);
        Future<T> future = executor.submit(new Callable<T>() {
            public T call() throws Exception {
                return feature.taskExec(callable);
            }
        });
        TaskData taskData = new TaskData(callable, future, feature);
        taskDataList.add(taskData);
        return taskData.future;
    }

    public Future enqueue(final Runnable runnable, final FeatureFaultIsolator feature) {
        return enqueue(new Callable<Object>() {
            public Object call() throws Exception {
                runnable.run();
                    return null;
            }
        }, feature);
    }

    public <T> T invoke(final Callable<T> callable, long timeout, final FeatureFaultIsolator feature) throws ExecutionException, InterruptedException, ServiceFaultException {
        if (!feature.isAvailable()) {
            throw new ServiceFaultException("Feature " + feature + " is disabled");
        }
        feature.taskAccepted(callable);
        Future<T> future = executor.submit(new Callable<T>() {
            public T call() throws Exception {
                return feature.taskExec(callable);
            }
        });
        try {
            return future.get(timeout, TimeUnit.MILLISECONDS);
        } catch (TimeoutException e) {
            feature.taskTimedOut(callable);
            throw new ServiceFaultException(e);
        }
    }

    public static <T> T invoke(final Callable<T> callable, FeatureFaultIsolator feature) throws Exception {
        if (!feature.isAvailable()) {
            throw new ServiceFaultException("Feature " + feature + " is disabled");
        }
        feature.taskAccepted(callable);
        return feature.taskExec(callable);
    }

    /**
     * @param totalExecutionTime - defines how long to wait STARTING FROM MOMENT OF CREATION OF THIS OBJECT
     * @throws ExecutionException - exception that had been generated by Runnable submitted before
     * @throws TimeoutException - wait for all Runnables to finish timed out
     * @throws InterruptedException - wait had been interrupted
     */
    public void waitToComplete(long totalExecutionTime) throws ExecutionException, TimeoutException, InterruptedException {
        for (TaskData taskData : taskDataList) {
            if (taskData.future.isDone()) {
                continue;
            }
            long timeLeft = totalExecutionTime - (System.currentTimeMillis() - startTime);
            if (timeLeft <= 0L) {
                throw new TimeoutException();
            }
            try {
                taskData.future.get(timeLeft, TimeUnit.MILLISECONDS);
            } catch (TimeoutException e) {
                if (handleTimeOut()) {
                    throw e;
                }
            }
        }
    }

    public boolean handleTimeOut() {
        boolean res = false;
        for (TaskData taskData : taskDataList) {
            if (!taskData.future.isDone()) {
                taskData.feature.taskTimedOut(taskData.callable);
                res = true;
            }
        }
        return res;
    }

    public static class TaskData {
        private final Callable<?> callable;
        private final Future<?> future;
        private final FeatureFaultIsolator feature;

        public TaskData(Callable<?> callable, Future<?> future, FeatureFaultIsolator feature) {
            this.callable = callable;
            this.future = future;
            this.feature = feature;
        }

        public Future<?> getFuture() {
            return future;
        }

        public FeatureFaultIsolator getFeature() {
            return feature;
        }


    }
}
